### ISSUE TITLE
About codebert-llvm-ic-v0

### ISSUE THREAD

**Issue by SoWhereAreYou** [iyaja/O4#1]
Hey，I‘m sorry to trouble you in this way.I just cannot find you.Can you tell me how could you pretained codebert-llvm?Was it a IR-Bert like Oscar?

**Comment by iyaja** [comment]
Hi! For this particular project, I did not explicitly pre-train CodeBERT on LLVM IR (though that is a good idea). The motivation for using CodeBERT was simply that it would be a better weight initialization than randomly initialized BERT. You can see the specific code I used to initialize the model [here](https://github.com/iyaja/O4/blob/a78dc536da564cd895ac9fa4429369f72dc738e2/train_cost.py#L40).

**Comment by SoWhereAreYou** [comment]
> Hi! For this particular project, I did not explicitly pre-train CodeBERT on LLVM IR (though that is a good idea). The motivation for using CodeBERT was simply that it would be a better weight initialization than randomly initialized BERT. You can see the specific code I used to initialize the model [here](https://github.com/iyaja/O4/blob/a78dc536da564cd895ac9fa4429369f72dc738e2/train_cost.py#L40).

Thank you，I had known it.
